# Generated by Django 5.1.6 on 2025-02-22 23:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaffeineLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('beverage_name', models.CharField(blank=True, max_length=100, null=True)),
                ('caffeine_amount_mg', models.FloatField()),
                ('beverage_size_ml', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('sugar_content_g', models.FloatField(blank=True, null=True)),
                ('calories_kcal', models.FloatField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caffeine_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
