# Generated by Django 5.1.6 on 2025-02-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caffeine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caffeinelog',
            old_name='caffeine_amount_mg',
            new_name='caffeine',
        ),
    ]
