# Generated by Django 5.1.6 on 2025-02-23 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caffeine', '0002_rename_caffeine_amount_mg_caffeinelog_caffeine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caffeinelog',
            old_name='caffeine',
            new_name='caffeine_mg',
        ),
    ]
