# Generated by Django 5.1.6 on 2025-02-22 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='caffeine_sensitivity',
            field=models.FloatField(default=0.5),
        ),
    ]
